# Generated by Django 2.1.7 on 2019-02-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_added', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_account', models.CharField(max_length=200)),
                ('instagram_account', models.CharField(max_length=200)),
                ('Twitter_account', models.CharField(max_length=200)),
                ('Github_account', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='username_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.User'),
        ),
    ]
