# Generated by Django 2.1.7 on 2019-02-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username_add',
        ),
    ]
