# Generated by Django 2.1.7 on 2019-02-25 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190225_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='acc',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
